### ISSUE TITLE
Perturbation on set R or test set?

### ISSUE THREAD

**Issue by ashrafabdul** [a-lucic/mc-brp#1]
From the algorithm in the paper I think the Tukeys Fence is calculated based on the features in set R but the code seems to be doing it on the entire test set.  I though set R was relevant since it would contain the reasonable range for the features, so including the entire test set R+L might include instances from L. Is this to allow for the possibility that some feature ranges in L might lead to reasonable errors?

https://github.com/a-lucic/mc-brp/blob/53d571c03d1679ba562a729ed6c023f7f4820994/src/main.py#L76

**Comment by a-lucic** [comment]
Great catch! I must have made this mistake when refactoring the code before putting it online. It's been updated now
